#!/usr/bin/env bash
# run-bot.sh [--armed] — the only path by which DRY_RUN=false ever reaches
# the liquidator binary on testnet.
#
# Two modes:
#
#   (no argument)  Dry run against target/testnet/pools.toml — the observe
#                  stage's own pools file, naming Blend's testnet pool.
#                  Reads that file; never writes it. Port 18081, database
#                  testnet_soak — the same two the observe stage's own
#                  long-running process already uses, since this is the
#                  supervised way to run exactly that stage. No signing key
#                  is read or needed: DRY_RUN is always true here.
#
#   --armed        DRY_RUN=false against target/testnet/pools.armed.toml,
#                  which this script (re)generates every run from
#                  target/testnet/testnet.env — the pool deploy.sh stood
#                  up. Port 18082, database testnet_armed. Requires
#                  testnet.env to exist and reads TESTNET_FILLER_SECRET_KEY
#                  from it into the child's environment only: never an
#                  argument (argv is world-readable), never echoed, never
#                  logged.
#
# require_testnet_network runs before either mode's own checks — "before
# anything" — so a misdirected TESTNET_RPC_URL refuses right here, for
# either mode, rather than ever reaching the binary. The binary itself only
# ever gets that same verified URL, exported as RPC_URL for the child.
#
# Execs the binary as its very last act (after redirecting output to this
# run's log file), so signals — SIGINT, SIGTERM — reach it directly rather
# than a shell wrapper that would have to relay them.
#
# TESTNET_RUN_PORT overrides the mode's own default port. Not part of the
# design either mode is meant to run with; it exists so this script can be
# verified without binding a port the long-running observe process already
# holds — see the container-level note in the soak's own runbook.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/testnet/lib.sh
source "${script_dir}/lib.sh"

if [ "$#" -gt 1 ]; then
	die "run-bot: too many arguments — usage: run-bot.sh [--armed]"
fi
armed=false
case "${1:-}" in
"") ;;
--armed) armed=true ;;
*) die "run-bot: unknown argument '$1' — usage: run-bot.sh [--armed]" ;;
esac

require_testnet_network

repo_root="$(cd "${script_dir}/../.." && pwd)"
binary="${repo_root}/target/debug/liquidator"
[ -x "${binary}" ] || die "run-bot: ${binary} does not exist or is not executable — build it first (cargo build)"

: "${DATABASE_URL:?run-bot: DATABASE_URL must be set in the environment}"

testnet_root="$(testnet_dir)"
mkdir -p "${testnet_root}"

# Swaps DATABASE_URL's own database name for this mode's, keeping whatever
# else the URL carries (host, credentials, a query string) untouched.
db_no_query="${DATABASE_URL%%\?*}"
db_query="${DATABASE_URL#"${db_no_query}"}"
db_server="${db_no_query%/*}"

if [ "${armed}" = true ]; then
	pool_env="${testnet_root}/testnet.env"
	[ -f "${pool_env}" ] \
		|| die "run-bot: --armed requires ${pool_env} — run scripts/testnet/deploy.sh first"
	# shellcheck source=/dev/null
	source "${pool_env}"
	for key in TESTNET_POOL TESTNET_XLM TESTNET_USDC TESTNET_BORROWER TESTNET_FILLER_SECRET_KEY; do
		[ -n "${!key:-}" ] || die "run-bot: ${pool_env} does not define ${key}"
	done

	# Regenerated every armed run from the addresses testnet.env names —
	# never target/testnet/pools.toml, which the observe stage owns and
	# this script never opens for writing in either mode.
	pools_file="${testnet_root}/pools.armed.toml"
	cat >"${pools_file}" <<EOF
# Generated by scripts/testnet/run-bot.sh --armed from ${pool_env}.
# Regenerated on every armed run — never hand-edit; re-run deploy.sh and
# this script instead.
[[pools]]
address = "${TESTNET_POOL}"
primary_asset = "${TESTNET_XLM}"
min_primary_collateral = "1000000000"
min_health_factor = 1.5
default_profit_bps = 100
fill_objective = "earliest-profitable"
supported_bid = ["${TESTNET_USDC}"]
supported_lot = ["*"]
EOF

	# The borrower deploy.sh funded took its position before this bot
	# existed, so no event of the range this run polls ever names it and
	# the tracker would follow nobody. A seed file is how an account that
	# is already in a pool becomes one the bot values — the sandbox test
	# writes the same one for the same reason.
	seed_file="${testnet_root}/seed.armed.toml"
	cat >"${seed_file}" <<EOF
# Generated by scripts/testnet/run-bot.sh --armed from ${pool_env}.
[accounts]
"${TESTNET_POOL}" = ["${TESTNET_BORROWER}"]
EOF

	mode=armed
	pool_address="${TESTNET_POOL}"
	port="${TESTNET_RUN_PORT:-18082}"
	db_name=testnet_armed
	log_file="${testnet_root}/armed.log"
else
	pools_file="${testnet_root}/pools.toml"
	[ -f "${pools_file}" ] \
		|| die "run-bot: ${pools_file} does not exist — the observe stage's pools file must exist first (see docs/testnet-soak.md)"

	# Optional here, unlike the armed mode: the observe stage follows a
	# pool whose borrowers are other people's, so the accounts worth
	# valuing are whatever `cargo run --example scan_borrowers` found in
	# the pool's own recent events. Without it the bot still runs and
	# follows every account that acts while it watches.
	seed_file="${testnet_root}/seed.toml"
	[ -f "${seed_file}" ] || seed_file=""

	mode=dry-run
	pool_address="$(sed -n 's/^address = "\(.*\)"/\1/p' "${pools_file}" | head -n1)"
	[ -n "${pool_address}" ] || die "run-bot: ${pools_file} names no pool address"
	port="${TESTNET_RUN_PORT:-18081}"
	db_name=testnet_soak
	log_file="${testnet_root}/dry-run.log"
fi

bot_database_url="${db_server}/${db_name}${db_query}"

log "mode: ${mode}"
log "network: testnet (${TESTNET_RPC_URL})"
log "pool: ${pool_address}"
log "log: ${log_file}"

export NETWORK=testnet
export RPC_URL="${TESTNET_RPC_URL}"
export POLL_INTERVAL_MS=5000
export LOG_FORMAT=json
export RUST_LOG="${RUST_LOG:-info,blend_liquidator=debug}"
export PORT="${port}"
export DATABASE_URL="${bot_database_url}"
export POOLS_FILE="${pools_file}"
# Always empty, never the default: SEED_URL's own default is the public
# analytics API, which answers for mainnet pools. A testnet run that asked
# it would seed mainnet accounts into a testnet pool.
export SEED_URL=""
if [ -n "${seed_file}" ]; then
	export SEED_FILE="${seed_file}"
	log "seed: ${seed_file}"
fi

if [ "${armed}" = true ]; then
	export DRY_RUN=false
	export FILLER_SECRET_KEY="${TESTNET_FILLER_SECRET_KEY}"
else
	export DRY_RUN=true
fi

# Everything from here on — the binary's own stdout/stderr — goes to the
# log file this run announced above, appended rather than truncated: two
# runs of the same mode leave one growing transcript rather than either
# silently discarding the other's.
exec >>"${log_file}" 2>&1
exec "${binary}"
